[workspace]
resolver = "3"
members = [
    "emergence",
    "2020/Rust",
    "2021/Rust",
    "2022/Rust",
    "2023/Rust",
    "2024/Rust",
    "aoc-common-rs",
]

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
debug = true
