name:                AdventOfCode2020
version:             0.1.0.0
github:              "Sciencentistguy/AdventOfCode"
license:             GPL-3
author:              "Jamie Quigley"
maintainer:          "jamie@quigley.xyz"
copyright:           "2021 Jamie Quigley"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Sciencentistguy/AdventOfCode#readme>

dependencies:
- base >= 4.7 && < 5
- text
- unix
- megaparsec
- split
- algebraic-graphs
- containers
- vector
- primitive
- lens
- comonad
- safe

default-extensions:
  BlockArguments
  GADTs

library:
  source-dirs: src

executables:
  AdventOfCode2020-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode2020

tests:
  AdventOfCode2020-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode2020
